print("______________ ")
print("(|           |)")
print("(|           |)")
print("(| ____  ___ |)")
print("(|| 0 | | 0 ||)")
print("(||___| |___||)")
print("(|      >    |)")
print("(| _________ |)")
print("(|____    ___|)")
print("     |    |    ")
print("               ")
print("The Staring Man")
